Yuki-TU/point-app-backend

- handler/health_check.go
- router/router.go
> add:#7 ヘルスチェックの実装

- .github/workflows/aws.yml
closes #9 
- docker imageのタグはlatestとcomitti idにしている
なし
なし
なし
> #9 githubactionの追加

- .github/workflows/aws.yml
- Makefile
- README.md
- _tools/mysql/seed.sql
- docker-compose.yml
- handler/register_user.go
closes #11 
* シードデータを用意
* makefileの更新
* seedコマンド用意
* README.mdの更新
* dbのホスト名更新
> #11 ドキュメント更新

- main.go
> update:#19 cors設定

- docs/openapi.yml
closes #22 
- ユーザ一覧を取得するAPI
- ユーザ仮登録のAPI
- ユーザ本登録のAPI
なし
なし
ユーザ一覧はAPIはとりあえずの値
> 認証系のswaggerの更新

- .github/workflows/aws.yml
- Makefile
- auth/jwt.go
> #28 githubaction workflow修正

- .github/workflows/aws.yml
- domain/interface.go
- domain/user/email.go
- domain/user/password.go
- handler/service.go
- handler/signin.go
- main.go
- repository/error.go
- router/router.go
- service/register_temporary_user.go
- service/register_user.go
- service/signin.go
closes #30 
- サインインAPI POST (/tokens)の実装
- 成功したらJWT返す
- 別端末でログインしたら他端末はログアウトされる
なし
パスワードのバリデーションはまだ欠けていないためTODO
> #30 サインインの実装

- docs/openapi.yml
closes #26 
以下のAPI追加
- アカウント情報取得・更新API
- パスワードリセットAPI
- メールアドレス仮本更新API
- ユーザ一覧取得API
- ポイント取引API
> #26 Swaggerの更新

- docs/openapi.yml
closes #35
- /tokens/{accessToken}をtokens/{userId}に変更
- headerにアクセストークンを含める形に変更
> update:#35 サインアウトAPIのSwagger更新

- _tools/mysql/schema.sql
- docs/openapi.yml
- domain/interface.go
- entity/user.go
- handler/get_users.go
- handler/service.go
- repository/user.go
- router/auth_router.go
- service/get_users.go
closes #40 
- ユーザー一覧を取得するエンドポイント作成
- 
レスポンス
```
{
"statusCode": 200,
"message": "取得成功しました。",
"data": {
"users": [
{
"familytName": "山田",
"familyNameKana": "ヤマダ",
"firstName": "太郎",
"firstNameKana": "タロウ",
"email": "yamada@sample.com",
"acquisitionPoint": 200
},
{
"familytName": "本郷",
"familyNameKana": "ホンゴウ",
"firstName": "奏",
"firstNameKana": "カナタ",
"email": "hongo@sample.com",
"acquisitionPoint": 1000000
},
{
"familytName": "本田",
"familyNameKana": "ホンダ",
"firstName": "美優",
"firstNameKana": "ミユ",
"email": "honda@sample.com",
"acquisitionPoint": 11100
}
]
}
}
```
なし
`api/v1/users`にアクセス
なし
> #40 ユーザ取得APIの実装

- docs/openapi.yml
> #42 Swagger更新

- docs/openapi.yml
- handler/get_account.go
- handler/service.go
- repository/user.go
- router/auth_router.go
- service/get_account.go
closes #45 
- Emailでユーザ情報取得SQLにacquitationpoint（累計獲得ポイント）を追加
- JWTよりEmailを判別し、ユーザ情報を取得
> #45 アカウント情報取得API

- domain/user/password.go
- repository/user.go
closes #45 
- ユーザ情報取得にパスワードを追加
PUSHする前にマージしてしまったので、漏れた分のみPRします
> #45 取得情報にパスワード追加

- docs/openapi.yml
- handler/get_users.go
closes #48 
- ユーザ情報取得プロパティにID追加
なし
なし
なし
> #48 add userid to the api for obtaining a list of users

- docs/openapi.yml
- handler/service.go
- handler/signout.go
- router/auth_router.go
- router/router.go
- service/signout.go
closes #50 
- PATHの変更
- `/tokens/{userId]`=>`/signout`
- openapi更新
- 不要なコード削除
- ステータスコードの修正
なし
なし
なし
> #50 サインアウトAPIのIF更新

- docs/openapi.yml
- main.go
- router/router.go
closes #52 
- main.go
- バックエンド開発環境時に指摘があった部分の修正
- openapi.yml
- router.go
ログイン画面
swaggerのみで確認しました。
特になし
> Feature/kudo/#52 ログインのエンドポイント修正

- auth/jwt.go
- docs/openapi.yml
- domain/interface.go
- domain/user/sendable_point.go
- handler/send_point.go
- handler/service.go
- repository/README.md
- repository/error.go
- repository/point.go
- repository/repository.go
- repository/transaction.go
- router/auth_router.go
- service/send_point.go
- service/signout.go
closes #55 
- 以下の処理フロー
1. ポイント送付かどうかを判断
2. ポイント取引を保存
3. 自身の送信可能ポイントを減らす
- 今回2つのテーブルを書き換えるためトランザクションを導入
なし
openapi修正してます
エラーの部分
> Feature/#55 ポイント送信APIの実装 

- docs/openapi.yml
passwordとメールアドレス更新APIを更新
closes #65 
* IFの更新
> #65 メールアドレス・パスワード更新APIのIF修正

- go.mod
- go.sum
- handler/register_temporary_user.go
- handler/register_user.go
- handler/reset_password.go
- handler/send_point.go
- handler/service.go
- handler/signin.go
- handler/update_password.go
- repository/error.go
- router/auth_router.go
- service/update_password.go
closes #67 
* パスワード変更APIの実装
* 新旧のパスワードが同じ場合エラー
* 旧パスワードが異なる場合はエラー
* 成功すれば、204を返す
なし
ライブラリを更新したので、`go mod tidy`を実行
なし
> Feature/#67 パスワード更新APIの実装

- docs/openapi.yml
- handler/update_password.go
> #70 パスワード更新APIのステータスコード修正

- .github/workflows/ci.yml
- .golangci.yml
- Dockerfile
- Makefile
closes #74 
* ciを以下に変更
https://github.com/reviewdog/action-golangci-lint
* gofmtに変更
* ローカルのフォーマッターを変更
なし
なし
なし
> Feature/#74 CIにおけるリンターの修正

- Makefile
- README.md
- go.mod
- go.sum
- handler/middleware.go
- main.go
- repository/repository.go
- repository/transaction.go
- router/auth_router.go
- router/router.go
- server.go
- server_test.go
- service/get_account.go
- service/get_users.go
- service/register_temporary_user.go
- service/register_user.go
- service/reset_password.go
- service/send_point.go
- service/signin.go
- service/signout.go
- service/update_password.go
closes #76 
* グレースフルシャットダウンの追加
* リクエストの途中でコンテナが終了してもレスポンスは返してからシャットダウンする
* サーバー起動は、ginが用意したメソッドを利用しなようにした
* サービス層にコンストラクタを追加
* New**で始まるコンストラクタを追加し、そちらを利用するように変更
* テストコードを追加
* テストコマンド
* サーバー起動のところのみテストコード
サーバー起動全て
新しいパッケージを入れたので、コンテナ内で以下のコマンドを実行
```sh
$ go mod tidy
```
テストは追加してますが、CIに組み込んだりするのは別チケットで対応する
> #76 グレースフルシャットダウンの実装

- docs/openapi.yml
- handler/update_account.go
closes #79 
アカウント更新成功時のステータスコードを200 → 201 へ変更
アカウント更新画面(作成中)
> Feature/#79 アカウント更新apiの成功ステータスコードの変更

- docs/openapi.yml
closes #87 
- お知らせ一覧取得API
- お知らせ詳細取得API
- お知らせ数取得API
> お知らせ関連openapi定義

- docs/openapi.yml
closes #89 
- jsonになっていたのをtext/event-streamに対応
- exampleの値を変更
> お知らせAPIのopenapi修正

- Makefile
- docs/openapi.yml
- handler/get_notifications.go
- handler/get_notifications_test.go
- handler/moq_test.go
- handler/service.go
- handler/testdata/get_notifications/200_rsp.json.golden
- handler/testdata/get_notifications/400_rsp.json.golden
- router/auth_router.go
- service/get_notifications.go
- service/get_notifications_test.go
closes #93 
- お知らせ一覧取得API
- カーソルページネーション対応
- nextTokenに指定が無い時は、ユーザテーブルより最新お知らせIDを取得する
- sizeはマストのバリデーションを入れている
- テストコードも記載
なし
なし
なし
> Feature/#93 お知らせ一覧取得API

- domain/model/temporary_user_test.go
- domain/model/time_test.go
- go.mod
- go.sum
- repository/user_test.go
- server_test.go
- service/get_notification_test.go
- service/get_notifications_test.go
- service/register_user_test.go
- service/update_temporary_email_test.go
- testutil/db.go
- testutil/handler.go
closes #101 
- testify/assetの導入
- cmpの削除
- アサーションの書き換え
テスト
なし
なし
> #101 introduction of assertion tools

- docs/openapi.yml
- docs/paths/users/[userId].yml
- domain/model/time_test.go
- handler/get_notification_test.go
- handler/get_notifications_test.go
- handler/register_user_test.go
- handler/update_temporary_email_test.go
- service/get_notification_test.go
- service/get_notifications_test.go
- service/update_temporary_email_test.go
closes #107 
- IFの定義
- テストが並行実行するようにパラレルメソッド追加
なし
なし
なし
> #107 define IF for delete user api

- .github/workflows/test.yml
- Dockerfile
- go.mod
> add:#112 update golang version

- .github/workflows/ci.yml
- Dockerfile
- go.mod
> #126 verson up go

- .github/workflows/ci.yml
- Makefile
- _tools/mysql/create_test_db.sh
- docker-compose.yml
- domain/interface.go
- domain/model/user.go
- repository/point_test.go
- repository/testdata/user.go
- repository/user.go
- repository/user_test.go
- service/get_notifications_test.go
- service/get_users.go
- service/moq_test.go
- testutil/db.go
- utils/clock/clock.go
closes #128 
* テスト用のDBを用意
* テスト初期データを入れるためのパッケージを追加（とりあえずユーザーテーブルのみ）
* リポジトリのテスト追加
なし
なし
なし
> #128 リポジトリのテスト修正

- docs/paths/users.yml
- domain/interface.go
- handler/get_users.go
- handler/moq_test.go
- handler/service.go
- repository/user.go
- repository/user_test.go
- service/get_users.go
- service/moq_test.go
- **add:#147 openapi追加**
- **add:#147 openapi追記**
- **add:#147 カーソルページネーション実装**
- **add:#147 テストのモック修正**
closes #147
- カーソルページネーション実装
-
> #147 ユーザー一覧カーソルページネーション実装

- LICENSE
> #149 add license

- Dockerfile
- go.mod
> add: go1.23
